site_name: XJU Math Wiki
theme:
  name: material

nav:
  - 首页: index.md
  - 校园: 校园.md
  - 保研: 保研.md
  - 考研: 考研.md
  
  - 资料(自动生成): resource-auto.md
  - 资料(手动补充): resource.md

  # - 课程目录:
  - 数学分析: 数学分析.md
  - 高等代数: 高等代数.md
  #   - 解析几何: 解析几何.md
  #   - 微分几何: 微分几何.md
  #   - 常微分方程: 常微分方程.md
  #   - 偏微分方程: 偏微分方程.md
  #   - 复变函数: 复变函数.md

  # - 数学分析: 数学分析.md
  # - 高等代数: 高等代数.md

  # - 解析几何: 解析几何.md
  - 微分几何: 微分几何.md

  # - 常微分方程: 常微分方程.md
  # - 偏微分方程: 偏微分方程.md

  - 复变函数: 复变函数.md
  # - 实变函数: 实变函数.md
  # - 泛函分析: 泛函分析.md
  # - 点集拓扑: 点集拓扑.md
  # - 近世代数: 近世代数.md

  - 概率论: 概率论.md
  # - 数理统计: 数理统计.md
  # - 运筹学: 运筹学.md
  # - 数值分析: 数值分析.md
  # - 图论: 图论.md

  # - 大学物理: 大学物理.md