name: Deploy MkDocs to gh-pages

on:
  push:
    branches:
      - main  # 触发工作流的分支
  workflow_dispatch:  # 允许手动触发工作流

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-python:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 使用 Python 3.x 版本
      
      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 更新资料目录
      - name: Update resource directory
        run: python update.py
      
      # 构建站点
      - name: Build MkDocs
        run: python -m mkdocs build
      
      # 部署到 gh-pages
      - name: Deploy to GitHub Pages
        run: python -m mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}